version: '3'
services:
  fastapi:
    build:
      context: .
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    networks:
      - prep
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload
#    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8050 --timeout 180

networks:
  prep:
    driver: bridge